### PR TITLE
Use spans

### LINKED ISSUE #5: Use Span<T>
The new [Span<T>](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md) type could provide some optimizations for exactly this library.

### PR DESCRIPTION
**Pull request by tabrath**
The methods taking a Span<byte> as the base methods the overloads taking a byte array are calling. Closes #5.

### CODE REVIEW

**Comment by hanabi1224** [comment]
Looks like the failure is caused by transient network error when installing mono in linux build  : (

**Comment by tabrath** [comment]
@hanabi1224 Yeah. Well, using 3 different platforms is just dumb, right? I'm eager to migrate 'em all to Azure Pipelines in the long run.

**Comment by tabrath** [comment]
Looks good to go, now.

**Comment by hanabi1224** [comment]
@tabrath  I don't have too much experience with azure pipelines, appveyor seems good enough for me in terms of coverage (windows / ubuntu), build speed, preinstalled softwares (e.g. for mono repo that uses rust to build native code and then package into dotnet nuget)

**Pull request merged**
